[project]
name = "data-science-assessment"
version = "0.1.0"
description = "VoiceScript Data Science assessment"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "instructor>=1.9.2",
    "jupyterlab>=4.4.4",
    "openai>=1.97.0",
    "python-dotenv>=1.1.1",
]
